# Generated by Django 3.1.7 on 2021-03-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeiotapi', '0003_auto_20210308_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_unsub_date', models.DateTimeField(auto_now_add=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', related_query_name='subscription', to='homeiotapi.appuser')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', related_query_name='subscription', to='homeiotapi.device')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SI', 'Imperial'), ('IN', 'Metric')], default='IN', max_length=2)),
                ('fail_notification', models.BooleanField(default=False)),
                ('threshold_notification', models.BooleanField(default=False)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpreferences', related_query_name='userpreference', to='homeiotapi.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='TempThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('max_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempthresholds', related_query_name='tempthreshold', to='homeiotapi.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='TempHumiThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('max_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('min_humi', models.DecimalField(decimal_places=3, max_digits=7)),
                ('max_humi', models.DecimalField(decimal_places=3, max_digits=7)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempHumithresholds', related_query_name='tempHumithreshold', to='homeiotapi.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='TempHumiDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('humi', models.DecimalField(decimal_places=3, max_digits=7)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temphumidatasets', related_query_name='temphumidataset', to='homeiotapi.device')),
            ],
        ),
        migrations.CreateModel(
            name='TempDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempdatasets', related_query_name='tempdataset', to='homeiotapi.device')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_if', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttonthresholds', related_query_name='buttonthreshold', to='homeiotapi.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_on', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttondatasets', related_query_name='buttondataset', to='homeiotapi.device')),
            ],
        ),
    ]
