# Generated by Django 3.1.7 on 2021-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeiotapi', '0004_buttondataset_buttonthreshold_subscription_tempdataset_temphumidataset_temphumithreshold_tempthresho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='unit',
            field=models.CharField(choices=[('IN', 'Imperial'), ('SI', 'Metric')], default='IN', max_length=2),
        ),
    ]
