# Generated by Django 3.1.7 on 2021-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeiotapi', '0005_auto_20210314_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='device_notification',
            field=models.BooleanField(default=True),
        ),
    ]
