# Generated by Django 3.1.7 on 2021-03-14 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeiotapi', '0006_subscription_device_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdataset',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
