# Generated by Django 3.1.7 on 2021-03-15 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeiotapi', '0007_auto_20210314_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttondataset',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temphumidataset',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
